name: Waka Readme

on:
  workflow_dispatch:
  schedule:
   # Runs at 22-hour intervals
    - cron: '0 */22 * * *'

jobs:
  update-readme:
    name: Update Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
          COMMIT_MESSAGE: "Update Metrics"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          COMMIT_BY_ME: "True"
          COMMIT_USERNAME: "Nisarg2061"
          COMMIT_EMAIL: "khodkenisarg@gmail.com"
          SHOW_UPDATED_DATE: "false"
